# config/database.yml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: touseeq

development:
  <<: *default
  database: bugzilla_development

test:
  <<: *default
  database: bugzilla_test

production:
  <<: *default
  database: your_app_production
  username: your_postgres_production_username
  password: <%= ENV['YOUR_APP_DATABASE_PASSWORD'] %>
